//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployeeDetail
    {
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string ManagerName { get; set; }
        public string JobTitle { get; set; }
        public string JobTypeRole { get; set; }
        public string NuildingAddress { get; set; }
        public int ManagerID { get; set; }
    }
}
